"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%6sv$2)yuyl9*m$*n)t-kthh!wwf%r^efukz^lmzmxgs6=ip88'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# CSRF settings for ngrok and external domains
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'http://localhost',
    'http://127.0.0.1',
]

# Ensure CSRF cookie is set on all responses
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read the cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Required for cross-site requests

# Application definition

INSTALLED_APPS = [
    # Unfold admin (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'catalog',
    'orders',
    'cart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cart session ID
CART_SESSION_ID = 'cart'

# Django Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "SHIMAI E-commerce",
    "SITE_HEADER": "SHIMAI Admin",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: "logo.svg",
    #     "dark": lambda request: "logo.svg",
    # },
    "SITE_LOGO": None,
    "SITE_SYMBOL": "shopping_bag",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "core.settings.environment_callback",
    "DASHBOARD_CALLBACK": "core.settings.dashboard_callback",
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50":  "253 251 245",   # почти белый, но тёплый
            "100": "250 246 235",   
            "200": "245 238 220",
            "300": "238 226 200",
            "400": "229 209 173",   # основной светлый бежевый
            "500": "210 184 148",   # основной цвет (средний телесный)
            "600": "186 157 120",
            "700": "158 129 96",
            "800": "128 103 78",
            "900": "102  82  63",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "ru": "🇷🇺",
            },
        },
    },
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Навигация",
                "separator": True,
                "items": [
                    {
                        "title": "Панель управления",
                        "icon": "dashboard",
                        "link": lambda request: "/admin/",
                    },
                ],
            },
            {
                "title": "Каталог",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Категории",
                        "icon": "category",
                        "link": lambda request: "/admin/catalog/category/",
                    },
                    {
                        "title": "Товары",
                        "icon": "inventory_2",
                        "link": lambda request: "/admin/catalog/product/",
                    },
                    # {
                    #     "title": "Галерея",
                    #     "icon": "photo_library",
                    #     "link": lambda request: "/admin/catalog/productgallery/",
                    # },
                ],
            },
            {
                "title": "Заказы",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Заказы",
                        "icon": "shopping_cart",
                        "link": lambda request: "/admin/orders/order/",
                    },
                    # {
                    #     "title": "Элементы заказов",
                    #     "icon": "receipt_long",
                    #     "link": lambda request: "/admin/orders/orderitem/",
                    # },
                ],
            },
            # {
            #     "title": "Система",
            #     "separator": True,
            #     "collapsible": True,
            #     "items": [
            #         {
            #             "title": "Пользователи",
            #             "icon": "people",
            #             "link": lambda request: "/admin/auth/user/",
            #         },
            #         {
            #             "title": "Группы",
            #             "icon": "group",
            #             "link": lambda request: "/admin/auth/group/",
            #         },
            #     ],
            # },
        ],
    },
    "TABS": [
        {
            "models": [
                "catalog.category",
                "catalog.product",
            ],
            "items": [
                {
                    "title": "Категории",
                    "link": lambda request: "/admin/catalog/category/",
                },
                {
                    "title": "Товары",
                    "link": lambda request: "/admin/catalog/product/",
                },
            ],
        },
    ],
}


def environment_callback(request):
    """
    Callback to show environment badge
    """
    return ["Development", "warning"] if DEBUG else ["Production", "danger"]


def dashboard_callback(request, context):
    """
    Callback to customize dashboard
    """
    context.update({})
    return context
