# Generated by Django 4.2.27 on 2026-01-09 08:13

from django.db import migrations


def migrate_existing_images(apps, schema_editor):
    """Migrate existing Product.image to ProductGallery"""
    Product = apps.get_model('catalog', 'Product')
    ProductGallery = apps.get_model('catalog', 'ProductGallery')

    for product in Product.objects.exclude(image=''):
        # Create gallery image from existing product image
        ProductGallery.objects.create(
            product=product,
            image=product.image,
            order=0,
            is_primary=True,
            alt_text=product.name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productgallery'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_images, reverse_code=migrations.RunPython.noop),
    ]
