# Generated by Django 4.2.1 on 2026-03-11 07:59

from django.db import migrations, models


def copy_name_to_color(apps, schema_editor):
    """Copy old 'name' (color) field into new 'color' field before unique constraint."""
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    ProductVariant.objects.filter(color='').update(color=models.F('name'))


def reverse_copy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['color', 'size'], 'verbose_name': 'Product variant', 'verbose_name_plural': 'Product variants'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price override'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Size'),
        ),
        migrations.RunPython(copy_name_to_color, reverse_copy),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('on_order', 'On Order'), ('best_seller', 'Best Seller'), ('new_arrival', 'New Arrival'), ('hot_deal', 'Hot Deal'), ('limited_stock', 'Limited Stock'), ('exclusive', "Exclusive to Lyn's Furniture")], default='in_stock', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
    ]
