# Generated by Django 4.2.27 on 2026-03-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariant_options_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariant', verbose_name='Variant'),
        ),
    ]
