# Generated by Django 4.2.27 on 2026-01-10 03:12

from django.db import migrations


def migrate_color_data(apps, schema_editor):
    """
    Migrate existing color and quantity data to ProductColor model
    """
    Product = apps.get_model('catalog', 'Product')
    ProductColor = apps.get_model('catalog', 'ProductColor')

    for product in Product.objects.all():
        if product.color:  # Only migrate if color exists
            # Create a ProductColor from the old color field
            ProductColor.objects.create(
                product=product,
                name=product.color,
                quantity=product.quantity,
                is_active=True
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - copy first color back to product
    """
    Product = apps.get_model('catalog', 'Product')
    ProductColor = apps.get_model('catalog', 'ProductColor')

    for product in Product.objects.all():
        first_color = product.colors.first()
        if first_color:
            product.color = first_color.name
            product.quantity = first_color.quantity
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_create_productcolor'),
    ]

    operations = [
        migrations.RunPython(migrate_color_data, reverse_migration),
    ]
