# Generated by Django 4.2.27 on 2026-01-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_migrate_color_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
