# Generated by Django 4.2.27 on 2026-01-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_old_color_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет/Размер товара',
                'verbose_name_plural': 'Цвета/Размеры товара',
                'ordering': ['name', 'size'],
            },
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='color',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariant', verbose_name='Цвет/Размер'),
        ),
    ]
