# Generated by Django 4.2.1 on 2026-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productvariant_remove_productgallery_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['name'], 'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товара'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
    ]
