# Generated by Django 4.2.27 on 2026-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_productvariant_size_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('on_order', 'On Order'), ('best_seller', 'Best Seller'), ('new_arrival', 'New Arrival'), ('hot_deal', 'Hot Deal'), ('limited_stock', 'Limited Stock')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
    ]
