# Generated by Django 4.2.1 on 2026-03-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Size'),
        ),
    ]
