# Generated by Django 4.2.27 on 2026-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_display_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вариант (Цвет/Размер)'),
        ),
    ]
