# Generated by Django 4.2.27 on 2026-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_variant_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone_call', 'Телефонный звонок'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='Способ связи'),
        ),
    ]
